Update docker-build.yml

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -58,10 +58,15 @@ jobs:
       - name: Aktualizacja deploymentu w k8s
         run: |
           IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.TIMESTAMP }}"
-          find kubernetes/k8s/deployments/ -type f -name "${{ env.DOCKER_IMAGE_NAME }}-deployment.yaml" | while read FILE
-          do
-              sed -i "s|image:.*|image: $IMAGE|g" $FILE
-          done
+          FILENAME=$(echo "${{ env.DOCKER_IMAGE_NAME }}" | tr '_' '-')
+          DEPLOYMENT_FILE="kubernetes/k8s/deployments/backend/${FILENAME}-deployment.yaml"
+          if [ -f "$DEPLOYMENT_FILE" ]; then
+            sed -i "s|image:.*|image: $IMAGE|g" "$DEPLOYMENT_FILE"
+          else
+            echo "Deployment file not found."
+            exit 1
+          fi
+
 
       - name: Commit and push changes
         run: |
